unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set -g default-shell /bin/zsh
set -g mouse on
set -g history-limit 50000

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g focus-events on
set -g allow-passthrough on
set -s extended-keys on

set -s set-clipboard external

setw -g aggressive-resize on

set -g status-style 'bg=default fg=colour248'
set -g status-left ''
set -g status-right ''
set -g pane-border-style 'fg=colour237'
set -g pane-active-border-style 'fg=colour237'
set -g message-style 'bg=default fg=colour255'

set -g mode-style 'bg=colour237 fg=colour255'

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'
bind -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi H send-keys -X start-of-line
bind -T copy-mode-vi L send-keys -X end-of-line

setw -g window-status-format '#[fg=colour244] #I:#W '
setw -g window-status-current-format '#[bg=colour211,fg=colour235,bold] #I:#W '

bind r source-file ~/.config/tmux/tmux.conf \; display 'tmux:config-reloaded'

unbind '"'
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind S choose-tree -s

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r Tab select-pane -t :.+

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

bind b break-pane -d

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""

run '~/.config/tmux/plugins/tpm/tpm'
